version: "3"

services:
    blogapi:
        image: blogapi
        volumes:
            - blogapi-sock:/BlogAPISock
            - ./python-uwsgi/uwsgi.ini:/app/uwsgi.ini:ro
    blognginx:
        image: blognginx
        ports:
            - "8000:80"
            - "8443:443"
        volumes:
            - blogapi-sock:/BlogAPISock
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./frontend:/var/www/frontend:ro
        depends_on:
            - blogapi

volumes:
    blogapi-sock:
