version: "3"

services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${PG_PASS}
            - PGDATA=${PGDATA}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - backend
    blogapi:
        image: bradleyzhou/blogapi
        networks:
            - frontend
            - backend
        volumes:
            - blogapi-sock:/BlogAPISock
        depends_on:
            - db
    blognginx:
        image: bradleyzhou/blognginx
        networks:
            - frontend
        volumes:
            - blogapi-sock:/BlogAPISock
        depends_on:
            - blogapi

volumes:
    blogapi-sock:

networks:
    frontend:
    backend:
